/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  subm:  LoopController
 *  model: RELbotSimple(1)
 *  expmt: RELbotSimple(1)
 *  date:  March 24, 2026
 *  time:  10:17:12 AM
 *  user:  University of Twente
 *  from:  -
 *  build: 5.1.1.13146
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/


