/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.h
 *  model: RELbotSimple
 *  expmt: RELbotSimple
 *  date:  March 31, 2026
 *  time:  11:48:45 AM
 *  user:  University of Twente
 *  from:  -
 *  build: 5.1.1.13146
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
